apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: app
  name: app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: app
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: app
    spec:
      containers:
      - image: kdldando/express-api-sample
        name: fastapi-sample
        envFrom:
          - configMapRef:
              name: app
          - secretRef:
              name: app
        resources: {}
status: {}
